name: Update version

on:
  push:
    paths: [ "VERSION" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  version-bump:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout required files
        uses: actions/checkout@v3

      - name: Update version
        run: |
          # Read Semver version from VERSION file
          VERSION=$(<VERSION)

          # Update version in package.json
          sed -i 's/"version": ".*"/"version": "'"$VERSION"'"/' package.json

          # Update version in Cargo.toml
          sed -i 's/version = ".*"/version = "'"$VERSION"'"/' Cargo.toml

      - name: Commit version update
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add package.json Cargo.toml
          git commit -m "Update version in package.json and Cargo.toml" || echo "No version bump needed."
          git push || echo "No changes to be pushed."

