name: Update version

on:
  push:
    paths: [ "VERSION" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  version-bump:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout required files
        uses: actions/checkout@v3

      - name: Update version
        id: update_version
        run: |
          # Read Semver version from VERSION file
          VERSION=$(<VERSION)
          echo "new_version=$VERSION" >> $GITHUB_OUTPUT
          # Update version in package.json
          sed -i 's/"version": ".*"/"version": "'"$VERSION"'"/' package.json

          # Update version in Cargo.toml
          sed -i 's/version = ".*"/version = "'"$VERSION"'"/' Cargo.toml

      - name: Commit version update
        run: |
          VERSION=${{ steps.update_version.outputs.new_version }}

          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package.json Cargo.toml
          git commit -m "Update version in package.json and Cargo.toml to $VERSION" || echo "No version bump needed."
          git push || echo "No changes to be pushed."

